services:
  # Web Service - FastAPI Backend
  - type: web
    name: bma-social-api
    runtime: python
    region: singapore
    plan: free # Change to 'starter' or higher for production
    buildCommand: |
      cd backend && pip install -r requirements.txt
    startCommand: |
      cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bma-social-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bma-social-redis
          property: connectionString
      # Add other environment variables in Render dashboard

  # Background Worker - Celery (Uncomment when needed)
  # - type: worker
  #   name: bma-social-worker
  #   runtime: python
  #   region: singapore
  #   plan: free
  #   buildCommand: |
  #     cd backend && pip install -r requirements.txt
  #   startCommand: |
  #     cd backend && celery -A app.worker worker --loglevel=info
  #   envVars:
  #     - key: PYTHON_VERSION
  #       value: 3.11.0
  #     - fromGroup: bma-social-api

# Databases (Create manually in Render dashboard for free tier)
# databases:
#   - name: bma-social-db
#     databaseName: bma_social
#     user: bma_social_user
#     region: singapore
#     plan: free # 'starter' for production
# 
#   - name: bma-social-redis
#     type: redis
#     region: singapore
#     plan: free # 'starter' for production